export const translations = {
    es: {
        appTitle: "PLAYERS LD",
        home: "Partido",
        fixture: "Fixture",
        tournaments: "Torneos",
        venues: "Canchas",
        rivals: "Rivales",
        myTeam: "Mi Equipo",
        logistics: "Utilería",
        stats: "Estadísticas",
        treasury: "Tesorería",
        help: "Ayuda",
        roster: "Plantilla",
        installApp: "Instalar App",
        nextMatch: "Próximo Partido",
        callUp: "Convocatoria",
        confirm: "Confirmar",
        doubt: "En Duda",
        absent: "Ausente",
        adminMatch: "🛠️ Cargar Datos / Admin",
        share: "Compartir",
        shareStats: "Compartir Resumen",
        myProfile: "Mi Perfil",
        matchStatus: {
            PROGRAMADO: "PROGRAMADO",
            FINALIZADO: "FINALIZADO",
            SUSPENDIDO: "SUSPENDIDO"
        },
        payment: {
            paid: "Pagado",
            partial: "Parcial",
            unpaid: "Debe"
        },
        search: "Buscar...",
        loading: "Cargando...",
        back: "Volver",
        genTeams: "⚽ Armar Equipos con IA",
        generating: "Generando...",
        adminOptions: "Opciones de Admin",
        openVoting: "Abrir Votación",
        closeVoting: "Cerrar Votación",
        votingOpen: "ABIERTAS",
        votingClosed: "CERRADAS",
        ratings: "Calificaciones"
    },
    en: {
        appTitle: "PLAYERS LD",
        home: "Match",
        fixture: "Fixture",
        tournaments: "Tournaments",
        venues: "Venues",
        rivals: "Opponents",
        myTeam: "My Team",
        logistics: "Logistics",
        stats: "Stats",
        treasury: "Treasury",
        help: "Help",
        roster: "Roster",
        installApp: "Install App",
        nextMatch: "Next Match",
        callUp: "Call Up",
        confirm: "Confirm",
        doubt: "Maybe",
        absent: "Absent",
        adminMatch: "🛠️ Admin / Data",
        share: "Share",
        shareStats: "Share Summary",
        myProfile: "My Profile",
        matchStatus: {
            PROGRAMADO: "SCHEDULED",
            FINALIZADO: "FINISHED",
            SUSPENDIDO: "SUSPENDED"
        },
        payment: {
            paid: "Paid",
            partial: "Partial",
            unpaid: "Unpaid"
        },
        search: "Search...",
        loading: "Loading...",
        back: "Back",
        genTeams: "⚽ AI Team Generator",
        generating: "Generating...",
        adminOptions: "Admin Options",
        openVoting: "Open Voting",
        closeVoting: "Close Voting",
        votingOpen: "OPEN",
        votingClosed: "CLOSED",
        ratings: "Ratings"
    },
    pt: {
        appTitle: "PLAYERS LD",
        home: "Partida",
        fixture: "Calendário",
        tournaments: "Torneios",
        venues: "Campos",
        rivals: "Rivais",
        myTeam: "Meu Time",
        logistics: "Logística",
        stats: "Estatísticas",
        treasury: "Tesouraria",
        help: "Ajuda",
        roster: "Elenco",
        installApp: "Instalar App",
        nextMatch: "Próxima Partida",
        callUp: "Convocação",
        confirm: "Confirmar",
        doubt: "Dúvida",
        absent: "Ausente",
        adminMatch: "🛠️ Admin / Dados",
        share: "Compartilhar",
        shareStats: "Compartilhar Resumo",
        myProfile: "Meu Perfil",
        matchStatus: {
            PROGRAMADO: "AGENDADO",
            FINALIZADO: "FINALIZADO",
            SUSPENDIDO: "SUSPENSO"
        },
        payment: {
            paid: "Pago",
            partial: "Parcial",
            unpaid: "Deve"
        },
        search: "Buscar...",
        loading: "Carregando...",
        back: "Voltar",
        genTeams: "⚽ Gerar Times com IA",
        generating: "Gerando...",
        adminOptions: "Opções de Admin",
        openVoting: "Abrir Votação",
        closeVoting: "Fechar Votação",
        votingOpen: "ABERTA",
        votingClosed: "FECHADA",
        ratings: "Avaliações"
    }
};